micronaut:
  application:
    name: mercadoLivro
datasources:
  default:
    url: jdbc:mysql://localhost:3306/mercadoLivro?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Nath@1308
    schema-generate: CREATE-DROP
    dialect: MYSQL
netty:
  default:
    allocator:
      max-order: 3
jpa.default.properties.hibernate.hbm2ddl.auto: update
flyway:
  datasources:
    default:
      locations: classpath:db/migrations
      enabled: true
